### ISSUE TITLE
Cannot install torchsparse under windows 11

### ISSUE THREAD

**Issue by DiamondGlassDrill** [One-2-3-45/One-2-3-45#16]
Somewhat everything can be installed in my mamba environment besides the 
torchsparse!!!
  File "...\mambaforge\envs\one2\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "...\torchsparse\setup.py", line 30, in
setup(
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_init_.py", line 107, in setup
return distutils.core.setup(**attrs)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\core.py", line 185, in setup
return run_commands(dist)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\core.py", line 201, in run_commands
dist.run_commands()
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\dist.py", line 969, in run_commands
self.run_command(cmd)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools\dist.py", line 1233, in run_command
super().run_command(command)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\dist.py", line 988, in run_command
cmd_obj.run()
File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\install.py", line 84, in run
self.do_egg_install()
File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\install.py", line 132, in do_egg_install
self.run_command('bdist_egg')
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\cmd.py", line 318, in run_command
self.distribution.run_command(command)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools\dist.py", line 1233, in run_command
super().run_command(command)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\dist.py", line 988, in run_command
cmd_obj.run()
File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
cmd = self.call_command('install_lib', warn_dir=0)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
self.run_command(cmdname)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\cmd.py", line 318, in run_command
self.distribution.run_command(command)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools\dist.py", line 1233, in run_command
super().run_command(command)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\dist.py", line 988, in run_command
cmd_obj.run()
File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
self.build()
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\command\install_lib.py", line 111, in build
self.run_command('build_ext')
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\cmd.py", line 318, in run_command
self.distribution.run_command(command)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools\dist.py", line 1233, in run_command
super().run_command(command)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\dist.py", line 988, in run_command
cmd_obj.run()
File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
_build_ext.run(self)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\command\build_ext.py", line 345, in run
self.build_extensions()
File "...\mambaforge\envs\one2\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
build_ext.build_extensions(self)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\command\build_ext.py", line 467, in build_extensions
self._build_extensions_serial()
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\command\build_ext.py", line 493, in _build_extensions_serial
self.build_extension(ext)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
_build_ext.build_extension(self, ext)
File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\command\build_ext.py", line 548, in build_extension
objects = self.compiler.compile(
File "...\mambaforge\envs\one2\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile
_write_ninja_file_and_compile_objects(
File "...\mambaforge\envs\one2\lib\site-packages\torch\utils\cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
_run_ninja_build(
File "...\mambaforge\envs\one2\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

Does anyone had the same issue?
I do have CUDA 11.8 and torch 2, everything installed as it was recommended. My card is an rtx 3090. I set the environments correctly as mentioned before. even direct checkout of version v1.4.0 and setup.py didn't work.

I really need the one2345 installed locally to proceed important tests. Thanks for the support!

**Comment by Dustinpro** [comment]
Thanks for your interest in our work! This error may be specific to Windows. It appears that this [post](https://github.com/mit-han-lab/torchsparse/issues/12#issuecomment-1412627402) in torchsparse could resolve the error.

**Comment by ioosssfd** [comment]
> Somewhat everything can be installed in my mamba environment besides the torchsparse!!! File "...\mambaforge\envs\one2\lib\subprocess.py", line 526, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "...\torchsparse\setup.py", line 30, in setup( File "...\mambaforge\envs\one2\lib\site-packages\setuptools_init_.py", line 107, in setup return distutils.core.setup(**attrs) File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\core.py", line 185, in setup return run_commands(dist) File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\core.py", line 201, in run_commands dist.run_commands() File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\dist.py", line 969, in run_commands self.run_command(cmd) File "...\mambaforge\envs\one2\lib\site-packages\setuptools\dist.py", line 1233, in run_command super().run_command(command) File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\dist.py", line 988, in run_command cmd_obj.run() File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\install.py", line 84, in run self.do_egg_install() File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\install.py", line 132, in do_egg_install self.run_command('bdist_egg') File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\cmd.py", line 318, in run_command self.distribution.run_command(command) File "...\mambaforge\envs\one2\lib\site-packages\setuptools\dist.py", line 1233, in run_command super().run_command(command) File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\dist.py", line 988, in run_command cmd_obj.run() File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run cmd = self.call_command('install_lib', warn_dir=0) File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command self.run_command(cmdname) File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\cmd.py", line 318, in run_command self.distribution.run_command(command) File "...\mambaforge\envs\one2\lib\site-packages\setuptools\dist.py", line 1233, in run_command super().run_command(command) File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\dist.py", line 988, in run_command cmd_obj.run() File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\install_lib.py", line 11, in run self.build() File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\command\install_lib.py", line 111, in build self.run_command('build_ext') File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\cmd.py", line 318, in run_command self.distribution.run_command(command) File "...\mambaforge\envs\one2\lib\site-packages\setuptools\dist.py", line 1233, in run_command super().run_command(command) File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\dist.py", line 988, in run_command cmd_obj.run() File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\build_ext.py", line 88, in run _build_ext.run(self) File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\command\build_ext.py", line 345, in run self.build_extensions() File "...\mambaforge\envs\one2\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions build_ext.build_extensions(self) File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\command\build_ext.py", line 467, in build_extensions self._build_extensions_serial() File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\command\build_ext.py", line 493, in _build_extensions_serial self.build_extension(ext) File "...\mambaforge\envs\one2\lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension _build_ext.build_extension(self, ext) File "...\mambaforge\envs\one2\lib\site-packages\setuptools_distutils\command\build_ext.py", line 548, in build_extension objects = self.compiler.compile( File "...\mambaforge\envs\one2\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile _write_ninja_file_and_compile_objects( File "...\mambaforge\envs\one2\lib\site-packages\torch\utils\cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects _run_ninja_build( File "...\mambaforge\envs\one2\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error compiling objects for extension
> 
> Does anyone had the same issue? I do have CUDA 11.8 and torch 2, everything installed as it was recommended. My card is an rtx 3090. I set the environments correctly as mentioned before. even direct checkout of version v1.4.0 and setup.py didn't work.
> 
> I really need the one2345 installed locally to proceed important tests. Thanks for the support!


Is the problem solved?

**Comment by DiamondGlassDrill** [comment]
Still working on it. But still no chance of success. Keep you posted

**Comment by DiamondGlassDrill** [comment]
Did the change: from [[Link]](https://github.com/pytorch/vision/issues/2360#issuecomment-883574291)
changing line 956 of /home/jiapy/virtualEnv/py3.6torch1.1/lib/python3.6/site-packages/torch/utils/cpp_extension.py from
['ninja', '-v']
to
['ninja', '--version']
seems solved the previous problem, but ...

**New error comes up:**

If I directly clone from repo and try to install it:
did also:
(pip setup.py clean before pip install .)

Error:
LINK : fatal error LNK1181: Input file "...\One-2-3-45\torchsparse\build\temp.win-amd64-cpython-310\Release\torchsparse\backend\convolution\convolution_cpu.obj" cannot be opened.
error: command '...\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181

Same case if I directly use the link: 
pip install --no-cache-dir git+https://github.com/mit-han-lab/torchsparse.git@v1.4.0

LINK : fatal error LNK1181: Input file "...\AppData\Local\Temp\pip-req-build-6_p3h42f\build\temp.win-amd64-cpython-310\Release\torchsparse\backend\convolution\convolution_cpu.obj" cannot be opened.
error: command '...\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181

Any idea?

**Comment by DiamondGlassDrill** [comment]
Any idea. As I trying it since ages. Until now no luck.

**Comment by DiamondGlassDrill** [comment]
Still no one getting the same issue?

**Comment by vule20** [comment]
I don't know about Windows but I experience the same problem while installing torchsparse in Ubuntu. I already found the solution for this and it turned out I missed some required packages. I solved simply by running **`apt-get install libsparsehash-dev`**

**Comment by CoraAI** [comment]
> install libsparsehash-dev

any solutions about windows 11? Really appreciate..

**Comment by csy2077** [comment]
I think it might have something to do with the cuda version, when I use the torch-2.4.0+cu121, which use a cuda version of 12.1, installing the torchsparse will output this error:
"""
RuntimeError:
    The detected CUDA version (11.7) mismatches the version that was used to compile
    PyTorch (12.1). Please make sure to use the same CUDA versions.
"""

then I try to degrade the cuda version to 11.7 using:
# CUDA 11.7
>>>pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1    

**this problems solved !**

however, when I use the version suggested:
>>>pip install --no-cache-dir torch==2.0.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
this command will use cuda **11.8** , which might be the reason cause the error

So the main point might be **the cuda must have to be 11.7**
