### ISSUE TITLE
torchsparse can not be installed.

### ISSUE THREAD

**Issue by TLB-MISS** [One-2-3-45/One-2-3-45#30]
First of all, thank you for sharing this great work.

However, I am currently having difficulty setting up the environment.
When installing torchsparse, the last step of Step 4, the following error occurs : 

```
...(omitted)
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-m7nljc02/setup.py", line 30, in <module>
          setup(
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/media/ssd1/sangwon/anaconda3/envs/12345/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torchsparse
  Running setup.py clean for torchsparse
Failed to build torchsparse
ERROR: Could not build wheels for torchsparse, which is required to install pyproject.toml-based projects
```

The latest version of torchsparse, 2.1.0, no longer supports the `PointTensor` used in one-2-3-45.
The above error occurs even when installing v2.0.0, the latest version that supports `PointTensor`.

**My environments**
Hardware : A5000
OS : Ubuntu 20.04
CUDA : 11.8
pytorch : 2.0.1

If anyone has solved this error, I would appreciate your help.

Thanks

**Comment by Dustinpro** [comment]
Please install torchsparse 1.4.0, as recommended in the Readme.
```
FORCE_CUDA=1 pip install --no-cache-dir git+https://github.com/mit-han-lab/torchsparse.git@v1.4.0
```

**Comment by TLB-MISS** [comment]
@Dustinpro 

Yes, what I meant was that the error occurs when installed as instructed in the readme.

> The latest version of torchsparse, 2.1.0, no longer supports the PointTensor used in one-2-3-45.
> The above error occurs even when installing v2.0.0, the latest version that supports PointTensor.

This means that all further attempts also failed.

**Comment by TLB-MISS** [comment]
I have no idea why, but I deleted all the environments and reinstalled and it was resolved.

**Comment by Yiveen** [comment]
Hello! @TLB-MISS I meet the same issue when I install the torchsparse. So you remove all of the conda environment and then reinstall them. Then the problem can be solved?

**Comment by TLB-MISS** [comment]
@Yiveen
Yes, I deleted and reinstalled the conda environment and the problem was resolved.
