### ISSUE TITLE
Error during running API

### ISSUE THREAD

**Issue by MrTornado24** [One-2-3-45/One-2-3-45#32]
Hi thanks for writing a API script. There is error when running it:

```
Traceback (most recent call last):
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/websockets/legacy/client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/fsspec/asyn.py", line 61, in _runner
    result[0] = await coro
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/gradio_client/client.py", line 1044, in _ws_fn
    async with websockets.connect(  # type: ignore
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/websockets/legacy/client.py", line 637, in __aenter__
    return await self
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/websockets/legacy/async_timeout.py", line 169, in __aexit__
    self._do_exit(exc_type)
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/websockets/legacy/async_timeout.py", line 252, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "debug.py", line 7, in <module>
    elevation_angle_deg = client.predict(
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/gradio_client/client.py", line 291, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/gradio_client/client.py", line 1120, in result
    return super().result(timeout=timeout)
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/gradio_client/client.py", line 793, in _inner
    predictions = _predict(*data)
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/gradio_client/client.py", line 822, in _predict
    result = utils.synchronize_async(self._ws_fn, data, hash_data, helper)
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/gradio_client/utils.py", line 517, in synchronize_async
    return fsspec.asyn.sync(fsspec.asyn.get_loop(), func, *args, **kwargs)  # type: ignore
  File "/hf_shared/hfai_envs/sunjingxiang/threestudio_0/lib/python3.8/site-packages/fsspec/asyn.py", line 104, in sync
    raise FSTimeoutError from return_result
fsspec.exceptions.FSTimeoutError
```

**Comment by Dustinpro** [comment]
TimeoutError may occur if our web demo automatically stops after 1 hour of inactivity. In that case, please click on the restart button to restart the demo. The API should work normally when the demo is running.
