### ISSUE TITLE
Bug maybe: about the 2-stage source view selection

### ISSUE THREAD

**Issue by Loping151** [One-2-3-45/One-2-3-45#37]
Occurred 24 times on a total task of 1026 generation.s 
I didn't look into it, but this is likely only a minor bug. 
Here is an example:
![23dbcf16aa7d5d2f9ee80cd3c10339c042bc4006c71119aebc08723eff01d631-8](https://github.com/One-2-3-45/One-2-3-45/assets/97866915/92bc0571-93ae-4637-b073-78d81ef89b9d)

**I know this is not a suitable case for 3D generation. I'm only here to report the potential bug.** 

```bash
2023-12-04 08:54:49,501 - root - ERROR - Exception occurred
Traceback (most recent call last):
  File "/home/loping151/Disks/TiPlus7100/projects/One-2-3-45/run.py", line 142, in <module>
    predict_multiview(shape_dir, args, os.path.join(path, png_name))
  File "/home/loping151/Disks/TiPlus7100/projects/One-2-3-45/run.py", line 102, in predict_multiview
    elev, stage1_imgs = stage1_run(model_zero123, device, shape_dir, input_256, scale=3, ddim_steps=75)
  File "/home/loping151/Disks/TiPlus7100/projects/One-2-3-45/run.py", line 45, in stage1_run
    gen_poses(exp_dir, polar_angle)
  File "/home/loping151/Disks/TiPlus7100/projects/One-2-3-45/utils/utils.py", line 131, in gen_poses
    img_ids, input_poses = get_poses(pose_est)
  File "/home/loping151/Disks/TiPlus7100/projects/One-2-3-45/utils/utils.py", line 109, in get_poses
    if init_elev <= 75:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2023-12-04 08:54:49,501 - root - INFO - Failed: 997/1026
2023-12-04 08:54:49,501 - root - INFO - Failed item: /home/***/Disks/TiPlus7100/data/prepared_data/window/23dbcf16aa7d5d2f9ee80cd3c10339c042bc4006c71119aebc08723eff01d631-8.png
```

**Comment by Dustinpro** [comment]
Thanks for pointing it out! Just fixed it in the commit.

**Comment by Loping151** [comment]
Hahaha 非常快处理，赞来自伤害👍
