### ISSUE TITLE
Any one who implemented on windows 10 

### ISSUE THREAD

**Issue by MHassan1122** [One-2-3-45/One-2-3-45#40]
I have GEFORCE RTX, tried my best to to run but raise some errors like windwo not yet supported for torch.compile

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.53 M params.
Keeping EMAs of 688.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "C:\Users\admin\One-2-3-45-master\run.py", line 115, in <module>
    predict_multiview(shape_dir, args)
  File "C:\Users\admin\One-2-3-45-master\run.py", line 83, in predict_multiview
    models = init_model(device, 'zero123-xl.ckpt', half_precision=args.half_precision)
  File "C:\Users\admin\One-2-3-45-master\utils\zero123_utils.py", line 45, in init_model
    models['turncam'] = torch.compile(load_model_from_config(config, ckpt, device=device)).half()
  File "C:\Users\admin\anaconda3\envs\flexicubes\lib\site-packages\torch\__init__.py", line 1441, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
  File "C:\Users\admin\anaconda3\envs\flexicubes\lib\site-packages\torch\_dynamo\eval_frame.py", line 413, in optimize
    check_if_dynamo_supported()
  File "C:\Users\admin\anaconda3\envs\flexicubes\lib\site-packages\torch\_dynamo\eval_frame.py", line 375, in check_if_dynamo_supported
    raise RuntimeError("Windows not yet supported for torch.compile")
RuntimeError: Windows not yet supported for torch.compile

**Comment by Dustinpro** [comment]
It is safe to delete the torch.compile() wrapping.

**Comment by MHassan1122** [comment]
i have done that, can you please tell me what type of image will be as a input like obj format or other.
i give png image means 2d it give me some results but i want to reconstruct 3d mesh from single image.
Thanks
