### ISSUE TITLE
Loading the diffusion checkpoint on colab

### ISSUE THREAD

**Issue by noureldinabdelalim** [One-2-3-45/One-2-3-45#46]
Whenever i run this command on colab:
!python run.py --img_path "/content/One-2-3-45/demo/demo_examples/01_wild_hydrant.png" --half_precision
The execution stops right after "Loading modal from checkpoint" and nothing happens so i am assuming it is something related to the checkpoint itself. Do you have an idea how i could fix it to work?
Thanks in advance

**Comment by Dustinpro** [comment]
If you are using Colab, you can follow the step-by-step instructions in `example.ipynb`. If the model fails to load, it is likely that the chosen GPU runtime has insufficient memory (less than 18GB).

**Comment by noureldinabdelalim** [comment]
there's still a problem with torch sparse, when i used the command in the read me file, it gave an error: "Building wheels for collected packages: torchsparse
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for torchsparse (setup.py) ... error
  ERROR: Failed building wheel for torchsparse
  Running setup.py clean for torchsparse
Failed to build torchsparse
ERROR: Could not build wheels for torchsparse, which is required to install pyproject.toml-based projects"

**Comment by noureldinabdelalim** [comment]
Also when I run without torchsparse, i get the images in the folder however I don't get the .ply file for the mesh, and I get this response: "Traceback (most recent call last):
  File "/content/One-2-3-45/reconstruction/exp_runner_generic_blender_val.py", line 18, in <module>
    from models.trainer_generic import GenericTrainer
  File "/content/One-2-3-45/reconstruction/models/trainer_generic.py", line 20, in <module>
    from models.sparse_neus_renderer import SparseNeuSRenderer
  File "/content/One-2-3-45/reconstruction/models/sparse_neus_renderer.py", line 17, in <module>
    from tsparse.torchsparse_utils import sparse_to_dense_channel
  File "/content/One-2-3-45/reconstruction/tsparse/torchsparse_utils.py", line 6, in <module>
    import torchsparse.nn.functional as F
ModuleNotFoundError: No module named 'torchsparse'
Mesh saved to: /content/One-2-3-45/exp/car/mesh.ply"

**Comment by Dustinpro** [comment]
Please show more details of the error. torchsparse requires that the CUDA version matches the version that was used to compile PyTorch. Please make sure to use the same CUDA versions.
